# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test ViewModel classes"
  lane :test_viewmodels do
    scan(
      scheme: "HDrinkTracker",
      clean: true,
      skip_build: true,
      code_coverage: true,
      derived_data_path: "./derived_data",
      xcargs: "-only-testing:HDrinkTrackerTests/ViewModelTests/*ViewModelTests"
    )
  end
end
